data:
  data_path: "dataset/kuangzj_bptest_0128/"

training:
  batch_size: 36
  num_workers: 8
  learning_rate: 0.001
  max_epochs: 200
  weight_decay: 0.0001
  seed: 42

scheduler:
  type: "none"
  T_max: 10
  min_lr: 0.001
  warmup_epochs: 5