data:
  data_path: "dataset/ultragood_0121/"
  position: "wrist"
  signal_type: "both"
  fs: 500  # sampling frequency
  sample_len: 5000      # 10 * fs = 10 * 500
  overlap: 0.8
  intra_session_split_ratio: 0.8
  n_channels: 21
  norm_2d: false

training:
  batch_size: 64
  num_workers: 8
  learning_rate: 0.001
  max_epochs: 200
  weight_decay: 0.01
  seed: 90

scheduler:
  type: "none"
  T_max: 20
  T_mult: 2
  min_lr: 0.0001

network:
  seq_len: 5000  # same as data.sample_len
  in_channels: 42
  dual_type: false
  reduce_channels: 8
  hidden_channels: [32, 64, 128]
  kernel_size: 7
  use_lstm: true
  lstm_hidden_size: 64
  lstm_num_layers: 2
  dropout: 0.2

loss:
  seq_len: 5000  # same as data.sample_len
  sigma: 10.0
  min_peak_distance: 250  # fs * 0.5 = 500 * 0.5
  max_peak_distance: 650  # fs * 1.3 = 500 * 1.3
  distance_weight: 0
  count_weight: 0

eval:
  count_err_thr: 0.8